server:
  port: 8080
  
info:
  component: Weather Playlist API

app:
  cache:
    temperature-values: 600 # time to live in seconds
  open-weather-map:
    key: 4cc3a3b4be4831f02cff2257752028e7
    unit: metric #[metric, imperial] kelvin is used by default
    api-url: http://api.openweathermap.org/data/2.5/weather?appid=${app.open-weather-map.key}&units=${app.open-weather-map.unit}
  spotify:
    api-url: https://api.spotify.com/v1
    auth:
      url: https://accounts.spotify.com/api
      client-id: 03f1769723834cd680011a0ff9d960de
      client-secret: 6af6d35702904a24b8348968ea166c6e
      
spring:
  redis:
    host: localhost
    port: 6379
feign:
  hystrix:
    enabled: true
hystrix:
    command:
      default.execution.isolation.thread.timeoutInMilliseconds: 4000
logging:
  level:
     com.ifood: DEBUG
      
---
# For deployment in Docker containers
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379